CREATE TABLE [dbo].[ACGPharmacyCodesPatientBulk] (
    [patient_id]                                      NVARCHAR (50)   NOT NULL,
    [age]                                             INT             NULL,
    [sex]                                             VARCHAR (1)     NULL,
    [line_of_business]                                VARCHAR (50)    NULL,
    [company]                                         VARCHAR (50)    NULL,
    [product]                                         VARCHAR (50)    NULL,
    [employer_group_id]                               VARCHAR (50)    NULL,
    [employer_group_name]                             VARCHAR (100)   NULL,
    [benefit_plan]                                    VARCHAR (50)    NULL,
    [health_system]                                   VARCHAR (50)    NULL,
    [pcp_id]                                          NVARCHAR (50)   NULL,
    [pcp_name]                                        VARCHAR (100)   NULL,
    [pcp_group_id]                                    NVARCHAR (50)   NULL,
    [pcp_group_name]                                  VARCHAR (100)   NULL,
    [pregnant]                                        SMALLINT        NULL,
    [delivered]                                       SMALLINT        NULL,
    [low_birthweight]                                 SMALLINT        NULL,
    [pharmacy_cost]                                   MONEY           NULL,
    [total_cost]                                      MONEY           NULL,
    [inpatient_hospitalization_count]                 SMALLINT        NULL,
    [emergency_visit_count]                           SMALLINT        NULL,
    [outpatient_visit_count]                          SMALLINT        NULL,
    [dialysis_service]                                SMALLINT        NULL,
    [nursing_service]                                 SMALLINT        NULL,
    [major_procedure]                                 INT             NULL,
    [pharmacy_cost_band]                              NVARCHAR (20)   NULL,
    [total_cost_band]                                 NVARCHAR (20)   NULL,
    [age_band]                                        NVARCHAR (20)   NULL,
    [acg_code]                                        INT             NULL,
    [resource_utilization_band]                       INT             NULL,
    [reference_unscaled_concurrent_weight]            FLOAT (53)      NULL,
    [reference_rescaled_concurrent_weight]            FLOAT (53)      NULL,
    [local_concurrent_weight]                         FLOAT (53)      NULL,
    [adg_codes]                                       VARCHAR (50)    NULL,
    [adg_vector]                                      VARCHAR (50)    NULL,
    [edc_codes]                                       VARCHAR (50)    NULL,
    [medc_codes]                                      VARCHAR (50)    NULL,
    [rxmg_codes]                                      VARCHAR (50)    NULL,
    [major_rxmg_codes]                                VARCHAR (50)    NULL,
    [major_adg_count]                                 VARCHAR (1)     NULL,
    [frailty_flag]                                    VARCHAR (1)     NULL,
    [hospital_dominant_count]                         VARCHAR (1)     NULL,
    [chronic_condition_count]                         VARCHAR (1)     NULL,
    [age_rel_macular_degeneration_condition]          VARCHAR (50)    NULL,
    [bipolar_disorder_condition]                      VARCHAR (50)    NULL,
    [bipolar_disorder_rx_gaps]                        VARCHAR (50)    NULL,
    [bipolar_disorder_mpr]                            VARCHAR (50)    NULL,
    [bipolar_disorder_csa]                            VARCHAR (50)    NULL,
    [bipolar_disorder_untreated_rx]                   VARCHAR (50)    NULL,
    [congestive_heart_failure_condition]              VARCHAR (50)    NULL,
    [congestive_heart_failure_rx_gaps]                VARCHAR (50)    NULL,
    [congestive_heart_failure_mpr]                    VARCHAR (50)    NULL,
    [congestive_heart_failure_csa]                    VARCHAR (50)    NULL,
    [congestive_heart_failure_untreated_rx]           VARCHAR (50)    NULL,
    [depression_condition]                            VARCHAR (50)    NULL,
    [depression_rx_gaps]                              VARCHAR (50)    NULL,
    [depression_mpr]                                  VARCHAR (50)    NULL,
    [depression_csa]                                  VARCHAR (50)    NULL,
    [depression_untreated_rx]                         VARCHAR (50)    NULL,
    [diabetes_condition]                              VARCHAR (50)    NULL,
    [diabetes_rx_gaps]                                VARCHAR (50)    NULL,
    [diabetes_mpr]                                    VARCHAR (50)    NULL,
    [diabetes_csa]                                    VARCHAR (50)    NULL,
    [diabetes_untreated_rx]                           VARCHAR (50)    NULL,
    [glaucoma_condition]                              VARCHAR (50)    NULL,
    [glaucoma_rx_gaps]                                VARCHAR (50)    NULL,
    [glaucoma_mpr]                                    VARCHAR (50)    NULL,
    [glaucoma_csa]                                    VARCHAR (50)    NULL,
    [glaucoma_untreated_rx]                           VARCHAR (50)    NULL,
    [human_immunodeficiency_virus_condition]          VARCHAR (50)    NULL,
    [human_immunodeficiency_virus_rx_gaps]            VARCHAR (50)    NULL,
    [human_immunodeficiency_virus_mpr]                VARCHAR (50)    NULL,
    [human_immunodeficiency_virus_csa]                VARCHAR (50)    NULL,
    [human_immunodeficiency_virus_untreated_rx]       VARCHAR (50)    NULL,
    [disorders_of_lipid_metabolism_condition]         VARCHAR (50)    NULL,
    [disorders_of_lipid_metabolism_rx_gaps]           VARCHAR (50)    NULL,
    [disorders_of_lipid_metabolism_mpr]               VARCHAR (50)    NULL,
    [disorders_of_lipid_metabolism_csa]               VARCHAR (50)    NULL,
    [disorders_of_lipid_metabolism_untreated_rx]      VARCHAR (50)    NULL,
    [hypertension_condition]                          VARCHAR (50)    NULL,
    [hypertension_rx_gaps]                            VARCHAR (50)    NULL,
    [hypertension_mpr]                                VARCHAR (50)    NULL,
    [hypertension_csa]                                VARCHAR (50)    NULL,
    [hypertension_untreated_rx]                       VARCHAR (50)    NULL,
    [hypothyroidism_condition]                        VARCHAR (50)    NULL,
    [hypothyroidism_rx_gaps]                          VARCHAR (50)    NULL,
    [hypothyroidism_mpr]                              VARCHAR (50)    NULL,
    [hypothyroidism_csa]                              VARCHAR (50)    NULL,
    [hypothyroidism_untreated_rx]                     VARCHAR (50)    NULL,
    [immuno_suppression_transplant_condition]         VARCHAR (50)    NULL,
    [immuno_suppression_transplant_rx_gaps]           VARCHAR (50)    NULL,
    [immuno_suppression_transplant_mpr]               VARCHAR (50)    NULL,
    [immuno_suppression_transplant_csa]               VARCHAR (50)    NULL,
    [immuno_suppression_transplant_untreated_rx]      VARCHAR (50)    NULL,
    [ischemic_heart_disease_condition]                VARCHAR (50)    NULL,
    [ischemic_heart_disease_rx_gaps]                  VARCHAR (50)    NULL,
    [ischemic_heart_disease_mpr]                      VARCHAR (50)    NULL,
    [ischemic_heart_disease_csa]                      VARCHAR (50)    NULL,
    [ischemic_heart_disease_untreated_rx]             VARCHAR (50)    NULL,
    [osteoporosis_condition]                          VARCHAR (50)    NULL,
    [osteoporosis_rx_gaps]                            VARCHAR (50)    NULL,
    [osteoporosis_mpr]                                VARCHAR (50)    NULL,
    [osteoporosis_csa]                                VARCHAR (50)    NULL,
    [osteoporosis_untreated_rx]                       VARCHAR (50)    NULL,
    [parkinsons_disease_condition]                    VARCHAR (50)    NULL,
    [parkinsons_disease_rx_gaps]                      VARCHAR (50)    NULL,
    [parkinsons_disease_mpr]                          VARCHAR (50)    NULL,
    [parkinsons_disease_csa]                          VARCHAR (50)    NULL,
    [parkinsons_disease_untreated_rx]                 VARCHAR (50)    NULL,
    [persistent_asthma_condition]                     VARCHAR (50)    NULL,
    [persistent_asthma_rx_gaps]                       VARCHAR (50)    NULL,
    [persistent_asthma_mpr]                           VARCHAR (50)    NULL,
    [persistent_asthma_csa]                           VARCHAR (50)    NULL,
    [persistent_asthma_untreated_rx]                  VARCHAR (50)    NULL,
    [rheumatoid_arthritis_condition]                  VARCHAR (50)    NULL,
    [rheumatoid_arthritis_rx_gaps]                    VARCHAR (50)    NULL,
    [rheumatoid_arthritis_mpr]                        VARCHAR (50)    NULL,
    [rheumatoid_arthritis_csa]                        VARCHAR (50)    NULL,
    [rheumatoid_arthritis_untreated_rx]               VARCHAR (50)    NULL,
    [schizophrenia_condition]                         VARCHAR (50)    NULL,
    [schizophrenia_rx_gaps]                           VARCHAR (50)    NULL,
    [schizophrenia_mpr]                               VARCHAR (50)    NULL,
    [schizophrenia_csa]                               VARCHAR (50)    NULL,
    [schizophrenia_untreated_rx]                      VARCHAR (50)    NULL,
    [seizure_disorders_condition]                     VARCHAR (50)    NULL,
    [seizure_disorders_rx_gaps]                       VARCHAR (50)    NULL,
    [seizure_disorders_mpr]                           VARCHAR (50)    NULL,
    [seizure_disorders_csa]                           VARCHAR (50)    NULL,
    [seizure_disorders_untreated_rx]                  VARCHAR (50)    NULL,
    [chronic_obstructive_pulmonary_disease_condition] VARCHAR (50)    NULL,
    [chronic_renal_failure_condition]                 VARCHAR (50)    NULL,
    [low_back_pain_condition]                         VARCHAR (50)    NULL,
    [unscaled_total_cost_resource_index]              FLOAT (53)      NULL,
    [rescaled_total_cost_resource_index]              FLOAT (53)      NULL,
    [probability_high_total_cost]                     FLOAT (53)      NULL,
    [unscaled_pharmacy_cost_resource_index]           FLOAT (53)      NULL,
    [rescaled_pharmacy_cost_resource_index]           FLOAT (53)      NULL,
    [probability_high_pharmacy_cost]                  DECIMAL (10, 2) NULL,
    [high_risk_unexpected_pharmacy_cost]              VARCHAR (1)     NULL,
    [probability_unexpected_pharmacy_cost]            FLOAT (53)      NULL,
    [majority_source_of_care_percent]                 FLOAT (53)      NULL,
    [majority_source_of_care_providers]               NVARCHAR (100)  NULL,
    [unique_provider_count]                           SMALLINT        NULL,
    [specialty_count]                                 VARCHAR (50)    NULL,
    [no_generalist]                                   VARCHAR (50)    NULL,
    [generic_drug_count]                              VARCHAR (1)     NULL,
    [probability_ip_hosp]                             FLOAT (53)      NULL,
    [probability_ip_hosp_6mos]                        FLOAT (53)      NULL,
    [probability_icu_hosp]                            FLOAT (53)      NULL,
    [probability_injury_hosp]                         FLOAT (53)      NULL,
    [probability_extended_hosp]                       FLOAT (53)      NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_ACGPharmacyCodesPatientBulk_Patient_id]
    ON [dbo].[ACGPharmacyCodesPatientBulk]([patient_id] ASC) WITH (FILLFACTOR = 25)
    ON [FG_Library_NCX];

