CREATE TABLE [dbo].[DataLoad_CodeSetNPIOtherProviderIdentifier] (
    [NPI]                                    NUMERIC (10) NULL,
    [Other Provider Identifier_1]            VARCHAR (20) NULL,
    [Other Provider Identifier_2]            VARCHAR (20) NULL,
    [Other Provider Identifier_3]            VARCHAR (20) NULL,
    [Other Provider Identifier_4]            VARCHAR (20) NULL,
    [Other Provider Identifier_5]            VARCHAR (20) NULL,
    [Other Provider Identifier_6]            VARCHAR (20) NULL,
    [Other Provider Identifier_7]            VARCHAR (20) NULL,
    [Other Provider Identifier_8]            VARCHAR (20) NULL,
    [Other Provider Identifier_9]            VARCHAR (20) NULL,
    [Other Provider Identifier_10]           VARCHAR (20) NULL,
    [Other Provider Identifier_11]           VARCHAR (20) NULL,
    [Other Provider Identifier_12]           VARCHAR (20) NULL,
    [Other Provider Identifier_13]           VARCHAR (20) NULL,
    [Other Provider Identifier_14]           VARCHAR (20) NULL,
    [Other Provider Identifier_15]           VARCHAR (20) NULL,
    [Other Provider Identifier_16]           VARCHAR (20) NULL,
    [Other Provider Identifier_17]           VARCHAR (20) NULL,
    [Other Provider Identifier_18]           VARCHAR (20) NULL,
    [Other Provider Identifier_19]           VARCHAR (20) NULL,
    [Other Provider Identifier_20]           VARCHAR (20) NULL,
    [Other Provider Identifier_21]           VARCHAR (20) NULL,
    [Other Provider Identifier_22]           VARCHAR (20) NULL,
    [Other Provider Identifier_23]           VARCHAR (20) NULL,
    [Other Provider Identifier_24]           VARCHAR (20) NULL,
    [Other Provider Identifier_25]           VARCHAR (20) NULL,
    [Other Provider Identifier_26]           VARCHAR (20) NULL,
    [Other Provider Identifier_27]           VARCHAR (20) NULL,
    [Other Provider Identifier_28]           VARCHAR (20) NULL,
    [Other Provider Identifier_29]           VARCHAR (20) NULL,
    [Other Provider Identifier_30]           VARCHAR (20) NULL,
    [Other Provider Identifier_31]           VARCHAR (20) NULL,
    [Other Provider Identifier_32]           VARCHAR (20) NULL,
    [Other Provider Identifier_33]           VARCHAR (20) NULL,
    [Other Provider Identifier_34]           VARCHAR (20) NULL,
    [Other Provider Identifier_35]           VARCHAR (20) NULL,
    [Other Provider Identifier_36]           VARCHAR (20) NULL,
    [Other Provider Identifier_37]           VARCHAR (20) NULL,
    [Other Provider Identifier_38]           VARCHAR (20) NULL,
    [Other Provider Identifier_39]           VARCHAR (20) NULL,
    [Other Provider Identifier_40]           VARCHAR (20) NULL,
    [Other Provider Identifier_41]           VARCHAR (20) NULL,
    [Other Provider Identifier_42]           VARCHAR (20) NULL,
    [Other Provider Identifier_43]           VARCHAR (20) NULL,
    [Other Provider Identifier_44]           VARCHAR (20) NULL,
    [Other Provider Identifier_45]           VARCHAR (20) NULL,
    [Other Provider Identifier_46]           VARCHAR (20) NULL,
    [Other Provider Identifier_47]           VARCHAR (20) NULL,
    [Other Provider Identifier_48]           VARCHAR (20) NULL,
    [Other Provider Identifier_49]           VARCHAR (20) NULL,
    [Other Provider Identifier_50]           VARCHAR (20) NULL,
    [Other Provider Identifier Type Code_1]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_2]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_3]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_4]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_5]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_6]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_7]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_8]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_9]  VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_10] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_11] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_12] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_13] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_14] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_15] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_16] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_17] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_18] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_19] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_20] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_21] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_22] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_23] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_24] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_25] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_26] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_27] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_28] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_29] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_30] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_31] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_32] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_33] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_34] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_35] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_36] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_37] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_38] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_39] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_40] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_41] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_42] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_43] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_44] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_45] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_46] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_47] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_48] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_49] VARCHAR (2)  NULL,
    [Other Provider Identifier Type Code_50] VARCHAR (2)  NULL,
    [Other Provider Identifier State_1]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_2]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_3]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_4]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_5]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_6]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_7]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_8]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_9]      VARCHAR (2)  NULL,
    [Other Provider Identifier State_10]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_11]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_12]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_13]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_14]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_15]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_16]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_17]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_18]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_19]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_20]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_21]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_22]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_23]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_24]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_25]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_26]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_27]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_28]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_29]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_30]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_31]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_32]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_33]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_34]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_35]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_36]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_37]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_38]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_39]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_40]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_41]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_42]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_43]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_44]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_45]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_46]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_47]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_48]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_49]     VARCHAR (2)  NULL,
    [Other Provider Identifier State_50]     VARCHAR (2)  NULL,
    [Other Provider Identifier Issuer_1]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_2]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_3]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_4]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_5]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_6]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_7]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_8]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_9]     VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_10]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_11]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_12]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_13]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_14]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_15]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_16]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_17]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_18]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_19]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_20]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_21]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_22]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_23]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_24]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_25]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_26]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_27]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_28]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_29]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_30]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_31]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_32]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_33]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_34]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_35]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_36]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_37]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_38]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_39]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_40]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_41]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_42]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_43]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_44]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_45]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_46]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_47]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_48]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_49]    VARCHAR (80) NULL,
    [Other Provider Identifier Issuer_50]    VARCHAR (80) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [UQ_DataLoad_NPIOtherProviderIdentifier_NPI]
    ON [dbo].[DataLoad_CodeSetNPIOtherProviderIdentifier]([NPI] ASC)
    ON [FG_Codesets];

