CREATE TABLE [dbo].[DataLoad_CodeSetNPIDetails] (
    [NPI]                                                                        NUMERIC (10) NULL,
    [Entity Type Code]                                                           NUMERIC (1)  NULL,
    [Replacement NPI]                                                            NUMERIC (10) NULL,
    [Employer Identification Number (EIN)]                                       VARCHAR (9)  NULL,
    [Provider Organization Name (Legal Business Name)]                           VARCHAR (70) NULL,
    [Provider Last Name (Legal Name)]                                            VARCHAR (35) NULL,
    [Provider First Name]                                                        VARCHAR (20) NULL,
    [Provider Middle Name]                                                       VARCHAR (20) NULL,
    [Provider Name Prefix Text]                                                  VARCHAR (5)  NULL,
    [Provider Name Suffix Text]                                                  VARCHAR (5)  NULL,
    [Provider Credential Text]                                                   VARCHAR (20) NULL,
    [Provider Other Organization Name]                                           VARCHAR (70) NULL,
    [Provider Other Organization Name Type Code]                                 VARCHAR (1)  NULL,
    [Provider Other Last Name]                                                   VARCHAR (35) NULL,
    [Provider Other First Name]                                                  VARCHAR (20) NULL,
    [Provider Other Middle Name]                                                 VARCHAR (20) NULL,
    [Provider Other Name Prefix Text]                                            VARCHAR (5)  NULL,
    [Provider Other Name Suffix Text]                                            VARCHAR (5)  NULL,
    [Provider Other Credential Text]                                             VARCHAR (20) NULL,
    [Provider Other Last Name Type Code]                                         NUMERIC (1)  NULL,
    [Provider First Line Business Mailing Address]                               VARCHAR (55) NULL,
    [Provider Second Line Business Mailing Address]                              VARCHAR (55) NULL,
    [Provider Business Mailing Address City Name]                                VARCHAR (40) NULL,
    [Provider Business Mailing Address State Name]                               VARCHAR (40) NULL,
    [Provider Business Mailing Address Postal Code]                              VARCHAR (20) NULL,
    [Provider Business Mailing Address Country Code (If outside U S )]           VARCHAR (2)  NULL,
    [Provider Business Mailing Address Telephone Number]                         VARCHAR (20) NULL,
    [Provider Business Mailing Address Fax Number]                               VARCHAR (20) NULL,
    [Provider First Line Business Practice Location Address]                     VARCHAR (55) NULL,
    [Provider Second Line Business Practice Location Address]                    VARCHAR (55) NULL,
    [Provider Business Practice Location Address City Name]                      VARCHAR (40) NULL,
    [Provider Business Practice Location Address State Name]                     VARCHAR (40) NULL,
    [Provider Business Practice Location Address Postal Code]                    VARCHAR (20) NULL,
    [Provider Business Practice Location Address Country Code (If outside U S )] VARCHAR (2)  NULL,
    [Provider Business Practice Location Address Telephone Number]               VARCHAR (20) NULL,
    [Provider Business Practice Location Address Fax Number]                     VARCHAR (20) NULL,
    [Provider Enumeration Date]                                                  DATE         NULL,
    [Last Update Date]                                                           DATE         NULL,
    [NPI Deactivation Reason Code]                                               VARCHAR (2)  NULL,
    [NPI Deactivation Date]                                                      DATE         NULL,
    [NPI Reactivation Date]                                                      DATE         NULL,
    [Provider Gender Code]                                                       VARCHAR (1)  NULL,
    [Authorized Official Last Name]                                              VARCHAR (35) NULL,
    [Authorized Official First Name]                                             VARCHAR (20) NULL,
    [Authorized Official Middle Name]                                            VARCHAR (20) NULL,
    [Authorized Official Title or Position]                                      VARCHAR (35) NULL,
    [Authorized Official Telephone Number]                                       VARCHAR (20) NULL,
    [Is Sole Proprietor]                                                         VARCHAR (1)  NULL,
    [Is Organization Subpart]                                                    VARCHAR (1)  NULL,
    [Parent Organization LBN]                                                    VARCHAR (70) NULL,
    [Parent Organization TIN]                                                    VARCHAR (9)  NULL,
    [Authorized Official Name Prefix Text]                                       VARCHAR (5)  NULL,
    [Authorized Official Name Suffix Text]                                       VARCHAR (5)  NULL,
    [Authorized Official Credential Text]                                        VARCHAR (20) NULL
);


GO
CREATE UNIQUE CLUSTERED INDEX [UQ_Dataload_NPIDeialis_NPI]
    ON [dbo].[DataLoad_CodeSetNPIDetails]([NPI] ASC)
    ON [FG_Codesets];

