CREATE TABLE [dbo].[LAB_IN_PROD_MBR] (
    [MBR_KEY]       VARCHAR (50) NULL,
    [LAB_SCR_DT]    VARCHAR (50) NULL,
    [LAB_CPT]       VARCHAR (50) NULL,
    [LAB_VALUE]     VARCHAR (50) NULL,
    [LAB_PN_IND]    VARCHAR (50) NULL,
    [LAB_NBR]       VARCHAR (50) NULL,
    [USE_LAB_VALUE] VARCHAR (50) NULL,
    [LOINC]         VARCHAR (50) NULL,
    [FILE_ID]       VARCHAR (50) NULL,
    [SRC_LOAD_DTM]  VARCHAR (50) NULL
);

