CREATE TABLE [dbo].[MEMBER_IN_PROD_MBR] (
    [MEM_NBR]                 VARCHAR (50) NOT NULL,
    [MEM_LNAME]               VARCHAR (50) NULL,
    [MEM_FNAME]               VARCHAR (50) NULL,
    [MEM_MNAME]               VARCHAR (50) NULL,
    [MEM_DOB]                 VARCHAR (50) NULL,
    [MEM_GENDER]              VARCHAR (50) NULL,
    [MEM_ADDR1]               VARCHAR (50) NULL,
    [MEM_ADDR2]               VARCHAR (50) NULL,
    [MEM_ADDR3]               VARCHAR (50) NULL,
    [MEM_CITY]                VARCHAR (50) NULL,
    [MEM_STATE]               VARCHAR (50) NULL,
    [MEM_ZIP]                 VARCHAR (50) NULL,
    [MEM_COUNTY]              VARCHAR (50) NULL,
    [MEM_PHONE]               VARCHAR (50) NULL,
    [MEM_SSN]                 VARCHAR (50) NULL,
    [MEM_HISP_ORIG]           VARCHAR (50) NULL,
    [MEM_NEED_INTERPRETER]    VARCHAR (50) NULL,
    [RACE_ID]                 VARCHAR (50) NULL,
    [HIC_NUMBER]              VARCHAR (50) NULL,
    [MRN_NUMBER]              VARCHAR (50) NULL,
    [GUARD_LNAME]             VARCHAR (50) NULL,
    [GUARD_FNAME]             VARCHAR (50) NULL,
    [GUARD_MNAME]             VARCHAR (50) NULL,
    [FIELD1]                  VARCHAR (50) NULL,
    [FIELD2]                  VARCHAR (50) NULL,
    [FIELD3]                  VARCHAR (50) NULL,
    [FIELD4]                  VARCHAR (50) NULL,
    [FIELD5]                  VARCHAR (50) NULL,
    [FIELD6]                  VARCHAR (50) NULL,
    [FIELD7]                  VARCHAR (50) NULL,
    [FIELD8]                  VARCHAR (50) NULL,
    [FIELD9]                  VARCHAR (50) NULL,
    [FIELD10]                 VARCHAR (50) NULL,
    [SPOKEN_LANGUAGE_SOURCE]  VARCHAR (50) NULL,
    [WRITTEN_LANGUAGE_SOURCE] VARCHAR (50) NULL,
    [OTHER_LANGUAGE_SOURCE]   VARCHAR (50) NULL,
    [SPOKEN_LANGUAGE_ID]      VARCHAR (50) NULL,
    [WRITTEN_LANGUAGE_ID]     VARCHAR (50) NULL,
    [OTHER_LANGUAGE_ID]       VARCHAR (50) NULL,
    [RACE_ETHNICITY_SOURCE]   VARCHAR (50) NULL,
    [FILE_ID]                 VARCHAR (50) NULL,
    CONSTRAINT [PK_MEMBER_IN_PROD_MBR] PRIMARY KEY CLUSTERED ([MEM_NBR] ASC) ON [FG_Library]
);

