CREATE TABLE [dbo].[NPOPatientSupplementalForm] (
    [PatientSupplementalFormID]  [dbo].[KeyID]    IDENTITY (1, 1) NOT NULL,
    [PatientID]                  [dbo].[KeyID]    NOT NULL,
    [DateofService]              DATETIME         NOT NULL,
    [RecordType]                 VARCHAR (1)      NOT NULL,
    [CodeTypeID]                 [dbo].[KeyID]    NULL,
    [MeasureID]                  [dbo].[KeyID]    NULL,
    [CodeValue]                  VARCHAR (20)     NULL,
    [ServiceCode]                VARCHAR (5)      NULL,
    [IsNumericResultType]        [dbo].[KeyID]    NULL,
    [LabOperator]                VARCHAR (20)     NULL,
    [LabResultValue]             DECIMAL (5, 2)   NULL,
    [LabResultTextID]            [dbo].[KeyID]    NULL,
    [EthnicityID]                [dbo].[KeyID]    NULL,
    [RaceID]                     [dbo].[KeyID]    NULL,
    [SpokenLanguageID]           [dbo].[KeyID]    NULL,
    [WrittenLanguageID]          [dbo].[KeyID]    NULL,
    [DateOfDeath]                [dbo].[UserDate] NULL,
    [CreatedByUserID]            [dbo].[KeyID]    NULL,
    [CreatedDate]                [dbo].[UserDate] NULL,
    [ServiceProviderNPI]         VARCHAR (50)     NULL,
    [ServiceProviderMILicenceNo] VARCHAR (50)     NULL,
    [PCPNPI]                     VARCHAR (50)     NULL,
    [PCPMILicenceNo]             VARCHAR (50)     NULL,
    CONSTRAINT [PK_NPOPatientSupplementalForm] PRIMARY KEY CLUSTERED ([PatientSupplementalFormID] ASC),
    CONSTRAINT [FK_NPOPatientSupplementalForm_CodeType] FOREIGN KEY ([CodeTypeID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_Ethnicity] FOREIGN KEY ([EthnicityID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_LabResultText] FOREIGN KEY ([LabResultTextID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_Measure] FOREIGN KEY ([MeasureID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_Patient] FOREIGN KEY ([PatientID]) REFERENCES [dbo].[Patient] ([PatientID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_SpokenLanguage] FOREIGN KEY ([SpokenLanguageID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalForm_WrittenLanguage] FOREIGN KEY ([WrittenLanguageID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID]),
    CONSTRAINT [FK_NPOPatientSupplementalFormm_Race] FOREIGN KEY ([RaceID]) REFERENCES [dbo].[NPOLkUp] ([LkUpCodeID])
);

