CREATE TABLE [dbo].[PRODUCT_ROLLUP_PROD_MBR] (
    [PRODUCT_ROLLUP_ID] VARCHAR (50) NULL,
    [PRODUCT_ID]        VARCHAR (50) NULL,
    [PROD_ORDER]        VARCHAR (50) NULL,
    [PROD_DESC]         VARCHAR (50) NULL,
    [FILE_ID]           VARCHAR (50) NULL
);

