CREATE TABLE [dbo].[PRODUCT_CURR_PROD_MBR] (
    [PRODUCT_ID]    VARCHAR (50) NULL,
    [PROD_DESC]     VARCHAR (50) NULL,
    [PROD_TYPE_ID]  VARCHAR (50) NULL,
    [PROD_LINE_ID]  VARCHAR (50) NULL,
    [PLAN_ID]       VARCHAR (50) NULL,
    [FILE_ID]       VARCHAR (50) NULL,
    [DB_SVR_NM]     VARCHAR (50) NULL,
    [SRC_SCHEMA_NM] VARCHAR (50) NULL,
    [RUN_SCHEMA_NM] VARCHAR (50) NULL,
    [ACTV_FLAG]     VARCHAR (50) NULL
);

