CREATE TABLE [dbo].[PROV_PRAC_TYPE_CURR_PROD_MBR] (
    [PRAC_TYPE_ID]  VARCHAR (50) NULL,
    [PROV_TAXONOMY] VARCHAR (50) NULL,
    [BOARD_CERT]    VARCHAR (50) NULL,
    [PROV_NBR]      VARCHAR (50) NULL,
    [PROV_SPEC]     VARCHAR (50) NULL,
    [PRIMARY_SPEC]  VARCHAR (50) NULL,
    [FILE_ID]       VARCHAR (50) NULL
);

