CREATE TABLE [dbo].[ProviderHierarchyDetail] (
    [ProviderHierarchyDetailID]      [dbo].[KeyID]    IDENTITY (1, 1) NOT NULL,
    [ProviderHierarchyID]            [dbo].[KeyID]    NOT NULL,
    [ParentProviderHierarchyLevelID] [dbo].[KeyID]    NOT NULL,
    [ParentProviderID]               [dbo].[KeyID]    NOT NULL,
    [ChildProviderID]                [dbo].[KeyID]    NOT NULL,
    [ChildProviderHierarchyLevelID]  [dbo].[KeyID]    NOT NULL,
    [BeginDate]                      DATE             NOT NULL,
    [EndDate]                        DATE             NOT NULL,
    [IsPrimary]                      BIT              NOT NULL,
    [DataSourceID]                   [dbo].[KeyID]    NULL,
    [DataSourceFileID]               [dbo].[KeyID]    NULL,
    [RecordTag_FileID]               VARCHAR (30)     NULL,
    [StatusCode]                     VARCHAR (1)      CONSTRAINT [DF_ProviderHierarchyDetail_StatusCode] DEFAULT ('A') NOT NULL,
    [CreatedByUserID]                [dbo].[KeyID]    NOT NULL,
    [CreatedDate]                    [dbo].[UserDate] CONSTRAINT [DF_ProviderHierarchyDetail_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [LastModifiedByUserID]           [dbo].[KeyID]    NULL,
    [LastModifiedDate]               [dbo].[UserDate] NULL,
    CONSTRAINT [PK_ProviderHierarchyDetail] PRIMARY KEY CLUSTERED ([ProviderHierarchyID] ASC, [ParentProviderID] ASC, [ChildProviderID] ASC),
    CONSTRAINT [FK_ProviderHierarchyDetail_ChildProvider] FOREIGN KEY ([ChildProviderID]) REFERENCES [dbo].[Provider] ([ProviderID]),
    CONSTRAINT [FK_ProviderHierarchyDetail_ChildProviderHierarchyLevel] FOREIGN KEY ([ChildProviderHierarchyLevelID]) REFERENCES [dbo].[ProviderHierarchyLevel] ([ProviderHierarchyLevelID]),
    CONSTRAINT [FK_ProviderHierarchyDetail_CodesetDataSource] FOREIGN KEY ([DataSourceID]) REFERENCES [dbo].[CodeSetDataSource] ([DataSourceId]),
    CONSTRAINT [FK_ProviderHierarchyDetail_DataSourceFile] FOREIGN KEY ([DataSourceFileID]) REFERENCES [dbo].[DataSourceFile] ([DataSourceFileID]),
    CONSTRAINT [FK_ProviderHierarchyDetail_ParentProvider] FOREIGN KEY ([ParentProviderID]) REFERENCES [dbo].[Provider] ([ProviderID]),
    CONSTRAINT [FK_ProviderHierarchyDetail_ParentProviderHierarchyLevel] FOREIGN KEY ([ParentProviderHierarchyLevelID]) REFERENCES [dbo].[ProviderHierarchyLevel] ([ProviderHierarchyLevelID]),
    CONSTRAINT [FK_ProviderHierarchyDetail_ProviderHierarchy] FOREIGN KEY ([ProviderHierarchyID]) REFERENCES [dbo].[ProviderHierarchy] ([ProviderHierarchyID]),
    CONSTRAINT [AK_ProviderHierarchyDetail] UNIQUE NONCLUSTERED ([ProviderHierarchyDetailID] ASC) WITH (FILLFACTOR = 100) ON [FG_Transactional_NCX]
);

