CREATE TABLE [dbo].[PROVIDER_LOCATION_CURR_PROD_MBR] (
    [PROV_NBR]    VARCHAR (50) NULL,
    [LOCATION_ID] VARCHAR (50) NULL,
    [LOC_NBR]     VARCHAR (50) NULL,
    [PRIMARY_YN]  VARCHAR (50) NULL,
    [FILE_ID]     VARCHAR (50) NULL
);

