CREATE TABLE [dbo].[PROVIDER_CURR_PROD_MBR] (
    [PROV_NBR]   VARCHAR (50) NULL,
    [PROV_TYPE]  VARCHAR (50) NULL,
    [CHASE_FLAG] VARCHAR (50) NULL,
    [PROV_RX]    VARCHAR (50) NULL,
    [PROV_LNAME] VARCHAR (50) NULL,
    [PROV_FNAME] VARCHAR (50) NULL,
    [PROV_MNAME] VARCHAR (50) NULL,
    [PROV_DEA]   VARCHAR (50) NULL,
    [PROV_TITLE] VARCHAR (50) NULL,
    [FIELD1]     VARCHAR (50) NULL,
    [FIELD2]     VARCHAR (50) NULL,
    [FIELD3]     VARCHAR (50) NULL,
    [FIELD4]     VARCHAR (50) NULL,
    [FIELD5]     VARCHAR (50) NULL,
    [FIELD6]     VARCHAR (50) NULL,
    [FIELD7]     VARCHAR (50) NULL,
    [FIELD8]     VARCHAR (50) NULL,
    [FIELD9]     VARCHAR (50) NULL,
    [FIELD10]    VARCHAR (50) NULL,
    [FILE_ID]    VARCHAR (50) NULL,
    [PROV_NPI]   VARCHAR (50) NULL
);

