CREATE TABLE [dbo].[Stg_ADTVisit] (
    [Patient_PrimaryId_Id]                        UNIQUEIDENTIFIER NULL,
    [SetId]                                       VARCHAR (200)    NULL,
    [PatientClass]                                VARCHAR (200)    NULL,
    [AssignedPatientLocation_Facility]            VARCHAR (200)    NULL,
    [AssignedPatientLocation_Description]         VARCHAR (200)    NULL,
    [AdmissionType]                               VARCHAR (200)    NULL,
    [AttendingDoctor_PersonIdentifier]            VARCHAR (200)    NULL,
    [AttendingDoctor_FamilyName]                  VARCHAR (200)    NULL,
    [AttendingDoctor_GivenName]                   VARCHAR (200)    NULL,
    [ReferringDoctor_PersonIdentifier]            VARCHAR (200)    NULL,
    [ReferringDoctor_FamilyName]                  VARCHAR (200)    NULL,
    [ReferringDoctor_GivenName]                   VARCHAR (200)    NULL,
    [HospitalService_Identifier]                  VARCHAR (200)    NULL,
    [HospitalService_NameOfCodingSystem]          VARCHAR (200)    NULL,
    [HospitalService_NameOfAlternateCodingSystem] VARCHAR (200)    NULL,
    [AdmittingDoctor_PersonIdentifier]            VARCHAR (200)    NULL,
    [AdmittingDoctor_FamilyName]                  VARCHAR (200)    NULL,
    [AdmittingDoctor_GivenName]                   VARCHAR (200)    NULL,
    [VisitNumber]                                 VARCHAR (200)    NULL,
    [AdmitDateTime]                               VARCHAR (200)    NULL,
    [DischargeDateTime]                           VARCHAR (200)    NULL,
    [AdmitReason_Identifier]                      VARCHAR (200)    NULL,
    [AdmitReason_TEXT]                            VARCHAR (200)    NULL,
    [AdmitReason_NameOfCodingSystem]              VARCHAR (200)    NULL,
    [AdmitReason_NameOfAlternateCodingSystem]     VARCHAR (200)    NULL,
    [ExpectedDischargeDateTime]                   VARCHAR (200)    NULL,
    [LengthOfInPatientStay]                       VARCHAR (200)    NULL,
    [EventType]                                   VARCHAR (10)     NULL
);

